Revert "Trying out older version of bottle that will not yield 'ImportError: cannot import name _compare_digest' at 'from operator import _compare_digest as compare_digest'"
This reverts commit 7c5acab3a4150471d03bd9b43f434490aa8a1a66.